<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'ac1d2460abc180c515e097ae8a7f7ea6',
  'DATABASE_URL' => 'mysql://root:user@127.0.0.1:3306/db?serverVersion=5.7',
  'MAILER_URL' => 'null://localhost',
);
